#!/bin/bash

PAYLOAD_FILE="install.tar.gz"
BUILD_FILE="install.tar"
rm -f $BUILD_FILE $PAYLOAD_FILE

tar cf $BUILD_FILE $(ls -1A)
tar --delete -f $BUILD_FILE .git
tar --delete -f $BUILD_FILE .gitignore
tar --delete -f $BUILD_FILE .gitattributes
tar --delete -f $BUILD_FILE README.md
tar --delete -f $BUILD_FILE build
tar --delete -f $BUILD_FILE install.sh
tar --delete -f $BUILD_FILE install.sh.in
tar --delete -f $BUILD_FILE tmp
tar --delete -f $BUILD_FILE tmux_install.sh

gzip $BUILD_FILE
if [[ "$?" -ne 0 ]]; then
    echo "ERROR: failed to create $PAYLOAD_FILE"
    exit 1    
fi

# Append binary data.
cp install.sh.in install.sh
echo "PAYLOAD:"   >> install.sh
cat $PAYLOAD_FILE >> install.sh

