#!/bin/bash

# TODO: Maybe create a deploy script for all dot files?
#
# http://developer.github.com/v3/repos/contents/#get-archive-link
#
# curl -L https://api.github.com/repos/seanmalloy/config-files/tarball > config-files.tar.gz

#Dependent Github Repos
#
# https://github.com/vim-scripts/delimitMate.vim.git

# 0. Basic validation
#   * do we have git?
#   * do we have curl?
REQUIRED_COMMANDS="git curl"
for $COMMAND in $REQUIRED_COMMAND; do
if [ -z `which $COMMAND` ]; then
    echo "Cannot find command $COMMAND"
    exit 1
fi
#   * is $HOME set?
if [ -z "$HOME"]; then
    echo "ENV HOME not set"
    exit 1
fi

# 1. Delete previous temp directory
# 2. Download tar ball
# 3. Downlad dependent repos
# 4. Deploy

